//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanda.AppTray.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scanda.AppTray.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al crear cron.
        /// </summary>
        internal static string cron_error {
            get {
                return ResourceManager.GetString("cron_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DB_Protector_16X16_01 {
            get {
                object obj = ResourceManager.GetObject("DB_Protector_16X16-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DB_Protector_32X32 {
            get {
                object obj = ResourceManager.GetObject("DB_Protector_32X32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DB_Protector_64X64 {
            get {
                object obj = ResourceManager.GetObject("DB_Protector_64X64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap devworms {
            get {
                object obj = ResourceManager.GetObject("devworms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error archivo inexistente.
        /// </summary>
        internal static string error_404 {
            get {
                return ResourceManager.GetString("error_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error comprimir arhivo.
        /// </summary>
        internal static string error_compress {
            get {
                return ResourceManager.GetString("error_compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error extension invalida.
        /// </summary>
        internal static string error_ext {
            get {
                return ResourceManager.GetString("error_ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta respaldos incorrecta.
        /// </summary>
        internal static string error_path {
            get {
                return ResourceManager.GetString("error_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error eliminando .zip.
        /// </summary>
        internal static string error_remove_file {
            get {
                return ResourceManager.GetString("error_remove_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: enviar Log: {0}.
        /// </summary>
        internal static string error_report {
            get {
                return ResourceManager.GetString("error_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espacio insuficiente.
        /// </summary>
        internal static string error_size {
            get {
                return ResourceManager.GetString("error_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error subir archivo.
        /// </summary>
        internal static string error_upload {
            get {
                return ResourceManager.GetString("error_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: enviar solicitud HTTP: {0}.
        /// </summary>
        internal static string http_error {
            get {
                return ResourceManager.GetString("http_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: abrir archivo de configuracion: {0}.
        /// </summary>
        internal static string load_config_file {
            get {
                return ResourceManager.GetString("load_config_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: abrir archivo de errores: {0}.
        /// </summary>
        internal static string load_errors_file {
            get {
                return ResourceManager.GetString("load_errors_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: autenticarse con API REST: {0}.
        /// </summary>
        internal static string login_api_error {
            get {
                return ResourceManager.GetString("login_api_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario con Status: {0}.
        /// </summary>
        internal static string login_status_error {
            get {
                return ResourceManager.GetString("login_status_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: obtener nombre de proceso con API.
        /// </summary>
        internal static string process_api {
            get {
                return ResourceManager.GetString("process_api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de proceso invalido.
        /// </summary>
        internal static string process_incorrect {
            get {
                return ResourceManager.GetString("process_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap QuotaCritical {
            get {
                object obj = ResourceManager.GetObject("QuotaCritical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap QuotaDownload {
            get {
                object obj = ResourceManager.GetObject("QuotaDownload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap QuotaError {
            get {
                object obj = ResourceManager.GetObject("QuotaError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap QuotaNearing {
            get {
                object obj = ResourceManager.GetObject("QuotaNearing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo descargado.
        /// </summary>
        internal static string success_download {
            get {
                return ResourceManager.GetString("success_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subida exitosa.
        /// </summary>
        internal static string success_upload {
            get {
                return ResourceManager.GetString("success_upload", resourceCulture);
            }
        }
    }
}
